# Docker Compose 설정
# 전체 스택을 로컬에서 실행하기 위한 설정

version: '3.8'

services:
  # 백엔드 API 서버
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8590:8590"
    environment:
      - DATABASE_URL=jdbc:sqlite:/data/vinventory.db
    volumes:
      - backend_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8590/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 프론트엔드 웹 앱
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8590

  # 데이터베이스 (선택사항 - PostgreSQL 사용 시)
  # database:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: vinventory
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  backend_data:
  # postgres_data:
